import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { FaCheck, FaTimes, FaBell, FaTrash, FaSave } from 'react-icons/fa';
import { reviewsApi, bookingsApi, adminApi } from '../services/api';
import { useAuth } from '../context/AuthContext';
import ContentManager from '../components/ContentManager';

const statuses = ['new', 'contacted', 'confirmed', 'completed', 'cancelled'];
const emptyEdit = { name: '', phone: '', email: '', eventType: '', date: '', time: '', message: '', status: 'new', adminNotes: '' };

export default function Admin() {
  const { user, ready, isAdmin } = useAuth();
  const [tab, setTab] = useState('overview');
  const [reviews, setReviews] = useState([]); const [bookings, setBookings] = useState([]); const [notifications, setNotifications] = useState([]);
  const [portfolio, setPortfolio] = useState([]); const [services, setServices] = useState([]); const [editingBooking, setEditingBooking] = useState(null); const [note, setNote] = useState('');
  const load = async () => { try { const [reviewResponse, bookingResponse, notificationResponse, portfolioResponse, serviceResponse] = await Promise.all([reviewsApi.pending(), bookingsApi.get(), bookingsApi.notifications(), adminApi.portfolio(), adminApi.services()]); setReviews(reviewResponse.data.data); setBookings(bookingResponse.data.data); setNotifications(notificationResponse.data.data); setPortfolio(portfolioResponse.data.data); setServices(serviceResponse.data.data); } catch (error) { setNote(error.response?.data?.message || 'Could not load admin content.'); } };
  useEffect(() => { if (isAdmin) load(); }, [isAdmin]);
  if (!ready) return <div className="section">Loading…</div>;
  if (!isAdmin) return <div className="section grid min-h-[55vh] place-items-center text-center"><div><h1 className="display text-4xl">Admin access only.</h1><Link className="btn-primary mt-5" to="/login">Sign in</Link></div></div>;
  const saveCatalog = async (type, id, data) => { const call = type === 'portfolio' ? (id ? adminApi.updatePortfolio(id, data) : adminApi.createPortfolio(data)) : (id ? adminApi.updateService(id, data) : adminApi.createService(data)); const response = await call; const setter = type === 'portfolio' ? setPortfolio : setServices; setter((items) => id ? items.map((item) => item.id === id ? response.data.data : item) : [response.data.data, ...items]); setNote('Saved successfully.'); };
  const removeCatalog = async (type, id) => { if (!confirm('Remove this item?')) return; await (type === 'portfolio' ? adminApi.deletePortfolio(id) : adminApi.deleteService(id)); (type === 'portfolio' ? setPortfolio : setServices)((items) => items.filter((item) => item.id !== id)); };
  const moderate = async (id, approve) => { await (approve ? reviewsApi.approve(id) : reviewsApi.reject(id)); setReviews((items) => items.filter((review) => review.id !== id)); };
  const saveBooking = async (event) => { event.preventDefault(); const response = await bookingsApi.update(editingBooking.id, editingBooking); setBookings((items) => items.map((item) => item.id === response.data.data.id ? response.data.data : item)); setEditingBooking(null); setNote('Booking updated successfully.'); load(); };
  const removeBooking = async (id) => { if (!confirm('Delete this booking enquiry?')) return; await bookingsApi.remove(id); setBookings((items) => items.filter((booking) => booking.id !== id)); setNote('Booking deleted.'); };
  const readNotification = async (notification) => { if (!notification.read) { await bookingsApi.readNotification(notification.id); setNotifications((items) => items.map((item) => item.id === notification.id ? { ...item, read: true } : item)); } };
  const unread = notifications.filter((notification) => !notification.read).length;
  return <div className="section"><p className="eyebrow">Admin workspace · {user.name}</p><h1 className="display mt-3 text-5xl">Content studio.</h1><p className="mt-3 text-[#786869]">Manage enquiries, reviews, catalogues, and editable page content.</p><div className="mt-8 flex flex-wrap gap-2"><button onClick={() => setTab('overview')} className={`btn ${tab === 'overview' ? 'bg-ink text-white' : 'bg-blush'}`}>Overview</button><button onClick={() => setTab('bookings')} className={`btn ${tab === 'bookings' ? 'bg-ink text-white' : 'bg-blush'}`}>Bookings</button><button onClick={() => setTab('reviews')} className={`btn ${tab === 'reviews' ? 'bg-ink text-white' : 'bg-blush'}`}>Reviews {reviews.length > 0 && `(${reviews.length})`}</button><button onClick={() => setTab('portfolio')} className={`btn ${tab === 'portfolio' ? 'bg-ink text-white' : 'bg-blush'}`}>Portfolio</button><button onClick={() => setTab('services')} className={`btn ${tab === 'services' ? 'bg-ink text-white' : 'bg-blush'}`}>Services</button><Link to="/admin/content" className="btn bg-rose text-white">Edit site copy</Link></div>{note && <p className="mt-5 text-sm text-rose">{note}</p>}
    {tab === 'overview' && <div className="mt-10 grid gap-5 md:grid-cols-3"><div className="card p-6"><p className="eyebrow">Bookings</p><p className="display mt-3 text-4xl">{bookings.length}</p><button onClick={() => setTab('bookings')} className="mt-4 text-sm text-rose">Manage enquiries</button></div><div className="card p-6"><p className="eyebrow">Pending reviews</p><p className="display mt-3 text-4xl">{reviews.length}</p><button onClick={() => setTab('reviews')} className="mt-4 text-sm text-rose">Moderate reviews</button></div><div className="card p-6"><p className="eyebrow flex items-center gap-2"><FaBell /> Notifications</p><p className="display mt-3 text-4xl">{unread}</p><p className="mt-4 text-sm text-[#786869]">Unread booking events</p></div><div className="card p-6 md:col-span-3"><h2 className="display text-2xl">Recent notifications</h2><div className="mt-4 space-y-3">{notifications.slice(0, 5).map((notification) => <button onClick={() => readNotification(notification)} className={`block w-full rounded-xl p-4 text-left text-sm ${notification.read ? 'bg-blush/40' : 'bg-blush'}`} key={notification.id}><span className="font-bold">{notification.title}</span><span className="ml-2 text-[#786869]">{notification.message}</span></button>)}{notifications.length === 0 && <p className="text-sm text-[#786869]">No notifications yet.</p>}</div></div></div>}
    {tab === 'bookings' && <section className="mt-10"><h2 className="display text-3xl">Booking enquiries</h2><div className="mt-6 space-y-4">{bookings.map((booking) => <article className="card p-5" key={booking.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="display text-2xl">{booking.name}</h3><p className="mt-1 text-sm text-[#786869]">{booking.eventType} · {booking.date} at {booking.time}</p><p className="mt-2 text-sm">{booking.email} · {booking.phone}</p></div><span className="rounded-full bg-blush px-3 py-1 text-xs font-bold uppercase text-rose">{booking.status}</span></div>{booking.message && <p className="mt-4 rounded-xl bg-blush/40 p-3 text-sm text-[#786869]">{booking.message}</p>}{booking.adminNotes && <p className="mt-3 text-sm"><b>Admin notes:</b> {booking.adminNotes}</p>}<div className="mt-5 flex flex-wrap gap-2"><button onClick={() => setEditingBooking({ ...emptyEdit, ...booking })} className="btn bg-blush">Edit booking</button><button onClick={() => removeBooking(booking.id)} className="btn bg-[#f5d8d5] text-rose"><FaTrash /> Delete</button></div></article>)}{bookings.length === 0 && <p className="text-sm text-[#786869]">No booking enquiries yet.</p>}</div></section>}
    {editingBooking && <div className="fixed inset-0 z-[70] grid place-items-center bg-black/60 p-5"><form onSubmit={saveBooking} className="card max-h-[90vh] w-full max-w-2xl overflow-auto p-7"><div className="flex items-center justify-between"><h2 className="display text-3xl">Edit booking</h2><button type="button" aria-label="Close" onClick={() => setEditingBooking(null)}><FaTimes /></button></div><div className="mt-6 grid gap-3 md:grid-cols-2">{['name', 'phone', 'email', 'eventType', 'date', 'time'].map((key) => <input required key={key} type={key === 'date' ? 'date' : key === 'time' ? 'time' : key === 'email' ? 'email' : 'text'} className="field" placeholder={key} value={editingBooking[key] || ''} onChange={(event) => setEditingBooking({ ...editingBooking, [key]: event.target.value })} />)}</div><select className="field mt-3" value={editingBooking.status} onChange={(event) => setEditingBooking({ ...editingBooking, status: event.target.value })}>{statuses.map((status) => <option key={status}>{status}</option>)}</select><textarea className="field mt-3 min-h-24" placeholder="Admin notes" value={editingBooking.adminNotes || ''} onChange={(event) => setEditingBooking({ ...editingBooking, adminNotes: event.target.value })} /><div className="mt-5 flex gap-3"><button className="btn-primary"><FaSave /> Save changes</button><button type="button" onClick={() => setEditingBooking(null)} className="btn bg-blush">Cancel</button></div></form></div>}
    {tab === 'reviews' && <section className="mt-10"><h2 className="display text-3xl">Reviews awaiting approval</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{reviews.map((review) => <article className="card p-5" key={review.id}>{review.image && <img src={review.image} alt="" className="mb-4 h-16 w-16 rounded-full object-cover" />}<p className="text-sm font-bold">{review.name} · {review.city}</p><h3 className="display mt-2 text-2xl">{review.title}</h3><p className="mt-2 text-sm leading-6 text-[#786869]">{review.description}</p><div className="mt-5 flex gap-2"><button onClick={() => moderate(review.id, true)} className="btn bg-[#dcebdc] text-green-800"><FaCheck /> Approve</button><button onClick={() => moderate(review.id, false)} className="btn bg-[#f5d8d5] text-rose"><FaTimes /> Reject</button></div></article>)}</div></section>}
    {tab === 'portfolio' && <section className="mt-10"><ContentManager type="portfolio" items={portfolio} onSave={(id, data) => saveCatalog('portfolio', id, data)} onDelete={(id) => removeCatalog('portfolio', id)} /></section>}
    {tab === 'services' && <section className="mt-10"><ContentManager type="services" items={services} onSave={(id, data) => saveCatalog('services', id, data)} onDelete={(id) => removeCatalog('services', id)} /></section>}
  </div>;
}
