import { useState } from 'react';
import { motion } from 'framer-motion';
import { FaInstagram, FaPhone, FaEnvelope, FaMapMarkerAlt } from 'react-icons/fa';
import SectionTitle from '../components/SectionTitle';
import { bookingsApi } from '../services/api';
import useSiteContent from '../hooks/useSiteContent';

const initial = { name: '', phone: '', email: '', eventType: 'Bridal', date: '', time: '', message: '' };
export default function Contact() {
  const site = useSiteContent();
  const [form, setForm] = useState(initial); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { await bookingsApi.create(form); setForm(initial); setNotice('Your enquiry is in. We will be in touch within 24 hours.'); } catch (error) { setNotice(error.response?.data?.message || 'Something went wrong. Please try again.'); } finally { setLoading(false); } };
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}><section className="section"><SectionTitle eyebrow="Contact" title="Let’s talk about your day." text="Tell us a little about what you’re planning and we’ll curate the right experience." /><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><aside className="rounded-[1.5rem] bg-ink p-8 text-white"><h2 className="display text-3xl">Come say hello.</h2><div className="mt-8 space-y-6 text-sm text-[#ead9d5]"><p className="flex gap-3"><FaPhone className="mt-1 text-[#e4aeb4]" />{site.phone}</p><p className="flex gap-3"><FaEnvelope className="mt-1 text-[#e4aeb4]" />{site.email}</p><p className="flex gap-3"><FaMapMarkerAlt className="mt-1 text-[#e4aeb4]" />{site.address}</p></div><a href={site.instagram} target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-full border border-[#846d6c] p-3"><FaInstagram /></a><div className="mt-10 grid h-40 place-items-center rounded-xl bg-[#4c3b3b] text-center text-xs text-[#cbb9b5]">Google Maps<br />Studio location</div></aside><form id="booking" onSubmit={submit} className="card p-6 md:p-8"><h2 className="display text-3xl">Reserve your date</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{[['name', 'Name'], ['phone', 'Phone'], ['email', 'Email']].map(([key, label]) => <input key={key} required type={key === 'email' ? 'email' : 'text'} className="field" placeholder={label} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} />)}<select className="field" value={form.eventType} onChange={(event) => setForm({ ...form, eventType: event.target.value })}>{['Bridal', 'Reception', 'Engagement', 'Party Makeup', 'Other'].map((option) => <option key={option}>{option}</option>)}</select><input required type="date" className="field" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /><input required type="time" className="field" value={form.time} onChange={(event) => setForm({ ...form, time: event.target.value })} /></div><textarea className="field mt-4 min-h-32" placeholder="Tell us about your plans" value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /><button disabled={loading} className="btn-primary mt-5 w-full">{loading ? 'Sending…' : 'Send enquiry'}</button>{notice && <p className="mt-4 text-center text-sm text-rose">{notice}</p>}</form></div></section></motion.div>;
}
