import { Link, NavLink, useLocation } from 'react-router-dom';
import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { FaBars, FaInstagram, FaSun, FaMoon, FaTimes } from 'react-icons/fa';
import useTheme from '../hooks/useTheme';
import useSiteContent from '../hooks/useSiteContent';
import { useAuth } from '../context/AuthContext';
import ScrollTop from '../components/ScrollTop';

const links = [['/', 'Home'], ['/about', 'About'], ['/portfolio', 'Portfolio'], ['/services', 'Services'], ['/reviews', 'Reviews'], ['/contact', 'Contact'], ['/faq', 'FAQ']];
export default function Layout({ children }) {
  const [open, setOpen] = useState(false); const [dark, setDark] = useTheme(); const { user, logout, isAdmin } = useAuth(); const loc = useLocation(); const site = useSiteContent();
  return <div className="min-h-screen dark:bg-[#241d1e] dark:text-[#fff8f4]"><header className="sticky top-0 z-50 border-b border-white/30 bg-cream/80 backdrop-blur-lg dark:bg-[#241d1e]/90"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 md:px-8"><Link to="/" className="display text-2xl tracking-tight">Maison <i className="text-rose">Rosé</i></Link><nav className="hidden items-center gap-6 lg:flex">{links.map(([to, name]) => <NavLink key={to} to={to} className={({ isActive }) => `text-sm transition ${isActive ? 'text-rose font-bold' : 'hover:text-rose'}`}>{name}</NavLink>)}{isAdmin && <NavLink to="/admin" className="text-xs font-bold text-rose">Workspace</NavLink>}</nav><div className="flex items-center gap-3"><button aria-label="Toggle theme" onClick={() => setDark(!dark)} className="rounded-full p-2 text-rose">{dark ? <FaSun /> : <FaMoon />}</button>{user ? <button onClick={logout} className="hidden text-sm text-rose sm:inline">Sign out</button> : <Link to="/login" className="hidden text-sm text-rose sm:inline">Sign in</Link>}<Link to="/contact#booking" className="btn-primary hidden sm:inline-flex">Book now</Link><button aria-label="Toggle navigation" className="lg:hidden" onClick={() => setOpen(!open)}>{open ? <FaTimes /> : <FaBars />}</button></div></div><AnimatePresence>{open && <motion.nav initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden border-t bg-cream px-5 dark:bg-[#241d1e] lg:hidden">{links.map(([to, name]) => <NavLink onClick={() => setOpen(false)} key={to} to={to} className="block py-3 text-sm">{name}</NavLink>)}{isAdmin && <NavLink to="/admin" className="block py-3 text-sm text-rose">Admin workspace</NavLink>}</motion.nav>}</AnimatePresence></header><main key={loc.pathname}>{children}</main><footer className="bg-ink px-5 py-14 text-[#f9eeea]"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-3"><div><p className="display text-3xl">Maison <i className="text-[#e4aeb4]">Rosé</i></p><p className="mt-4 max-w-xs text-sm leading-7 text-[#cbb9b5]">{site.footerDescription}</p></div><div><p className="eyebrow text-[#e4aeb4]">Come say hello</p><p className="mt-4 text-sm">{site.email}</p><p className="mt-2 text-sm">{site.phone}</p><p className="mt-2 text-sm text-[#cbb9b5]">{site.address}</p></div><div><p className="eyebrow text-[#e4aeb4]">Explore</p><div className="mt-4 flex flex-col gap-2 text-sm">{links.slice(1, 5).map(([to, name]) => <Link className="hover:text-[#e4aeb4]" key={to} to={to}>{name}</Link>)}</div><a href={site.instagram} target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-full border border-[#846d6c] p-3"><FaInstagram /></a></div></div><p className="mx-auto mt-12 max-w-7xl border-t border-[#5d4948] pt-6 text-xs text-[#a9928e]">© 2026 Maison Rosé. Made for luminous moments.</p></footer><ScrollTop /></div>;
}
