import express from 'express';
import { createServer } from 'node:http';
import cors from 'cors';
import morgan from 'morgan';
import dotenv from 'dotenv';
import reviewsRouter from './routes/reviews.routes.js';
import bookingsRouter from './routes/bookings.routes.js';
import portfolioRouter from './routes/portfolio.routes.js';
import servicesRouter from './routes/services.routes.js';
import authRouter from './routes/auth.routes.js';
import adminRouter from './routes/admin.routes.js';
import siteRouter from './routes/site.routes.js';
import { connectDatabase } from './config/database.js';
import { initializeDatabase } from './services/database.service.js';
import { notFound, errorHandler } from './middleware/error.middleware.js';
import { initializeSocket } from './realtime/socket.js';

dotenv.config();
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' }));
app.use(express.json({ limit: '1mb' }));
app.use('/uploads', express.static('uploads'));
app.use(morgan('dev'));
app.get('/api/health', (_, res) => res.json({ success: true, message: 'Maison Rosé API is running' }));
app.use('/api/reviews', reviewsRouter);
app.use('/api/bookings', bookingsRouter);
app.use('/api/portfolio', portfolioRouter);
app.use('/api/services', servicesRouter);
app.use('/api/auth', authRouter);
app.use('/api/admin', adminRouter);
app.use('/api/site', siteRouter);
app.use(notFound); app.use(errorHandler);
const port = process.env.PORT || 5000;
connectDatabase().then(initializeDatabase).then(() => {
	const httpServer = createServer(app);
	initializeSocket(httpServer);
	httpServer.listen(port, () => console.log(`API listening on ${port}`));
}).catch((error) => {
	console.error('Unable to connect to MySQL:', error.message);
	process.exit(1);
});
