import axios from 'axios';
export const apiBase = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const api=axios.create({baseURL:apiBase});
api.interceptors.request.use((config)=>{const token=localStorage.getItem('maison-token');if(token)config.headers.Authorization=`Bearer ${token}`;return config;});
export const imageUrl=(image)=>image?.startsWith('/')?`${apiBase.replace('/api','')}${image}`:image;
export const authApi={login:(d)=>api.post('/auth/login',d),register:(d)=>api.post('/auth/register',d),google:(credential)=>api.post('/auth/google',{credential}),me:()=>api.get('/auth/me')};
export const reviewsApi={get:()=>api.get('/reviews'),pending:()=>api.get('/reviews/pending'),create:(d)=>api.post('/reviews',d),approve:(id)=>api.put(`/reviews/${id}/approve`),reject:(id)=>api.delete(`/reviews/${id}/reject`)};
export const bookingsApi={create:(d)=>api.post('/bookings',d),get:(params)=>api.get('/bookings',{params}),update:(id,d)=>api.put(`/bookings/${id}`,d),remove:(id)=>api.delete(`/bookings/${id}`),notifications:(params)=>api.get('/bookings/notifications',{params}),readNotification:(id)=>api.put(`/bookings/notifications/${id}/read`),availability:()=>api.get('/bookings/availability'),setAvailability:(date,d)=>api.put(`/bookings/availability/${date}`,d),removeAvailability:(date)=>api.delete(`/bookings/availability/${date}`)}; export const catalogApi={portfolio:()=>api.get('/portfolio'),services:()=>api.get('/services')}; export const siteApi={get:()=>api.get('/site')};
export const adminApi={site:()=>api.get('/admin/site'),updateSite:(d)=>api.put('/admin/site',d),portfolio:()=>api.get('/admin/portfolio'),services:()=>api.get('/admin/services'),createPortfolio:(d)=>api.post('/admin/portfolio',d),updatePortfolio:(id,d)=>api.put(`/admin/portfolio/${id}`,d),deletePortfolio:(id)=>api.delete(`/admin/portfolio/${id}`),createService:(d)=>api.post('/admin/services',d),updateService:(id,d)=>api.put(`/admin/services/${id}`,d),deleteService:(id)=>api.delete(`/admin/services/${id}`)};
